version: '3'
services:
  json-server:
    container_name: json-server-container
    image: json-server-image
    build: ./db
    ports:
        - "3000:3000"
    volumes:
        - ./db/db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0
